import { z } from 'zod';
export const id = z.string().uuid();
const text = z.string().trim().min(1).max(200);
export const targetSchema = z.object({targetType:z.string().regex(/^[A-Z][A-Z0-9_]{1,63}$/),targetId:z.string().min(1).max(128)}).strict();
export const loginSchema = z.object({email:z.string().email().max(254).transform(s=>s.toLowerCase()),password:z.string().min(1).max(256)}).strict();
export const contextSchema = z.object({membershipId:id}).strict();
export const userSchema = z.object({id,email:z.string().email(),name:z.string(),active:z.boolean()}).strict();
export const sessionSchema = z.object({user:userSchema,context:z.object({organizationId:id,siteId:id.nullable(),membershipId:id}),permissions:z.array(z.string()),memberships:z.array(z.object({id,organizationId:id,siteId:id.nullable()}))});
export const organizationSchema = z.object({id,name:z.string(),active:z.boolean()});
export const activationSchema = z.object({active:z.boolean()}).strict();
export const workflowSchema = z.object({name:text,description:z.string().max(4000).optional(),resourceType:targetSchema.shape.targetType}).strict();
export const assignmentSchema = z.object({strategy:z.literal('USER'),userId:id}).strict();
export const stepSchema = z.object({key:z.string().regex(/^[a-z][a-z0-9_-]{0,63}$/),name:text,type:z.literal('USER_TASK').default('USER_TASK'),configuration:z.object({assignment:assignmentSchema}).strict(),position:z.number().int().min(0).default(0),initial:z.boolean().default(false),terminal:z.boolean().default(false)}).strict();
export const transitionSchema = z.object({fromStepId:id,toStepId:id,outcome:z.string().regex(/^[a-z][a-z0-9_-]{0,63}$/).default('complete')}).strict();
export const startWorkflowSchema = targetSchema.extend({workflowId:id}).strict();
export const taskSchema = targetSchema.extend({title:text,description:z.string().max(4000).optional(),assignedToUserId:id,dueAt:z.string().datetime().optional()}).strict();
export const assignTaskSchema = z.object({assignedToUserId:id}).strict();
export const completeTaskSchema = z.object({outcome:z.string().regex(/^[a-z][a-z0-9_-]{0,63}$/).default('complete')}).strict();
export const uploadSchema = targetSchema.extend({originalFilename:z.string().min(1).max(255).refine(s=>!/[\x00-\x1f/\\]/.test(s),'Invalid filename'),contentType:z.enum(['application/pdf','text/plain','image/png','image/jpeg','application/octet-stream']),size:z.number().int().positive().max(104857600),checksum:z.string().regex(/^[A-Za-z0-9+/]{43}=$/,'Expected base64 SHA-256')}).strict();
export const taskResponseSchema = z.object({id,type:z.enum(['ACTION','WORKFLOW']),title:z.string(),status:z.enum(['PENDING','IN_PROGRESS','COMPLETED','CANCELLED']),assignedToUserId:id,targetType:z.string(),targetId:z.string(),workflowInstanceId:id.nullable(),workflowInstanceStepId:id.nullable(),completedAt:z.string().nullable(),completedById:id.nullable()}).passthrough();
export const workflowResponseSchema = z.object({id,name:z.string(),resourceType:z.string(),currentVersion:z.number().nullable()}).passthrough();
export const instanceResponseSchema = z.object({id,workflowId:id,workflowVersionId:id,targetType:z.string(),targetId:z.string(),status:z.enum(['PENDING','IN_PROGRESS','COMPLETED','CANCELLED','REJECTED'])}).passthrough();
export const fileResponseSchema = z.object({id,originalFilename:z.string(),contentType:z.string(),size:z.number(),status:z.enum(['PENDING','AVAILABLE','REJECTED'])}).passthrough();
export type LoginInput = z.infer<typeof loginSchema>;
export type CreateWorkflowInput = z.infer<typeof workflowSchema>;
export type StepInput = z.infer<typeof stepSchema>;
export type TransitionInput = z.infer<typeof transitionSchema>;
export type StartWorkflowInput = z.infer<typeof startWorkflowSchema>;
export type TaskInput = z.infer<typeof taskSchema>;
export type UploadInput = z.infer<typeof uploadSchema>;
export type CurrentSession = z.infer<typeof sessionSchema>;
